name: "devskim"

on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze_driver:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/DevSkim-Action@v1
    - name: Filter CodeQL Results
      uses: advanced-security/filter-sarif@v1
      with:
          # Exclude Microsoft and third party sources
          patterns: -packages/**/*
          input: devskim-results.sarif
          output: devskim-results.sarif
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: devskim-results.sarif
