name: "devskim"

on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze_driver:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/DevSkim-Action@v1
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: devskim-results.sarif
